### PR TITLE
fixed the bugs in urdfreader.cc file

### PR DESCRIPTION
**Pull request by rua0ra1**
Hi,
I have fixed the bugs or typos mentioned in the
- Fixed the bug described in [issue #85 ](https://github.com/rbdl/rbdl/issues/85).
and I have tested them. I believe it will solve the issues with urdfreader if you have ros.

Thank you

### CODE REVIEW

**Comment by ju6ge** [comment]
Hi,

thanks for taking care of this. I have tested your patch using a `ros:latest` container. Sadly the build fails for me …

Steps to reproduce in RBDL Source directory:
```sh
podman run -it -v "$PWD:$PWD" -w "$PWD" docker.io/ros:latest

mkdir build && cd build

cmake -DRBDL_USE_ROS_URDF_LIBRARY=ON -DRBDL_BUILD_ADDON_URDFREADER=ON ..

make -j 16
```

Result:
```
addons/urdfreader/urdfreader.cc:13:12: fatal error: urdf_model/model.h: No such file or directory
   13 |   #include <urdf_model/model.h>
      |            ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

That being said, I am not into ROS and have no clue about different versions of ROS, how and where they put their headers and so on. Originally RBDL shipped a vendored version of ROS URDF Libraries which where horribly out of date. That is why we switched to a different `UrdfParser` Library. We keept ROS build stuff in RBDL to enable the usage, but we can not test against all versions of ROS and ensure compatibility!

Our CI is not complaining about the patch and I don't see a reason not to merge this. Since it definitily fixes the part of the build that creates the `urdfparser` library for ros. Just not the part where the parser is used to construct an RBDL Model from the parsed urdf file. 

Any thoughts on this?

When merged I can also create a new release for RBDL including your patch, if you like ;)

**Comment by RamCharanThota** [comment]
Hi @ju6ge Felix.

All good mate. I am glad to contribute. 

You are right. there are multiple versions of ROS and each version is dependent on specific Ubuntu release.

I have tested this bug fix with Ubuntu 20.04 and ROS noetic. I believe it should also work for anyone who is using Ubuntu 20.04  and ROS noetic.

i didn't quite get it what you mean by
 " Just not the part where the parser is used to construct an RBDL Model from the parsed urdf file." can you elaborate bit more. If you mean that there are still some issues with  construct an RBDL model from urdf file. I didn't get the chance to test it. But, I am happy to have a look into it.

Sure go ahead. I think it would be better if we can mention that this fix is tested on ROS noetic only. So that people won't waste their time :P

Thank you.

**Comment by rua0ra1** [comment]
Hi @ju6ge ,
I am wondering are there any other issues to be taken care of to merge this pull request ?. Thank you

**Comment by ju6ge** [comment]
Hi,

sorry for the delay in getting back to you. The last few weeks have been pretty crazy in terms of work for me. Anyway, I would like to move forward on this. But I want to make sure that things work as expected on ROS.

For this purposes I have tested compiling the code using a ROS container.  This is to make sure that code will work in an unmodified ROS. If steps to get RBDL are missing they need to be documentet in the README.

# ROS tests
Sadly I am encountering two different errors depending on the ROS Version.

Steps to reproduce: 
1. Recursively cloned RBDL-Repositiory with your update applied.

## ROS Latest
```sh
# start clean ROS latest environment
$ podman run -it --rm -v $PWD:$PWD -w $PWD docker.io/ros:latest 

# install missing dependencies
$ apt update
$ apt install libboost-dev

# run RBDL build
$ mkdir build && cd build
$ cmake -DRBDL_USE_ROS_URDF_LIBRARY=ON -DRBDL_BUILD_ADDON_URDFREADER=ON ..
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0")  
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /work/build_ros
$ make -j
…
/work/addons/urdfreader/urdfreader.cc:13:12: fatal error: urdf_model/model.h: No such file or directory
   13 |   #include <urdf_model/model.h>
      |            ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/build.make:76: addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/urdfreader.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/all] Error 2
```

So here the include path for `urdf_model/model.h` is not found.  This is fixable by changing the include path to `urdf/model.h`. But the I run into a new error in the next line:

```
/work/addons/urdfreader/urdfreader.cc:14:12: fatal error: urdf_parser/urdf_parser.h: No such file or directory
   14 |   #include <urdf_parser/urdf_parser.h>
```

This is not easily resolvable because, I tried different versions of the path, but with no success:

At least in ROS i can find the header located here: `/opt/ros/jazzy/include/urdf_parser_plugin/urdf_parser_plugin/parser.h`. But hardcoding this path is not a solution here. Probably the library needs to be correctly imported via cmake.


## ROS noetic
```sh
# start clean ROS noetic environment
$ podman run -it --rm -v $PWD:$PWD -w $PWD docker.io/ros:noetic

# install missing dependencies
$ apt update
$ apt install libeigen3-dev

# run RBDL build
$ mkdir build && cd build
$ cmake -DRBDL_USE_ROS_URDF_LIBRARY=ON -DRBDL_BUILD_ADDON_URDFREADER=ON ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- ROS found: /opt/ros/noetic/share/ros
-- Using CATKIN_DEVEL_PREFIX: /work/build_ros/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Found PY_em: /usr/lib/python3/dist-packages/em.py  
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /work/build_ros/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Could NOT find urdf (missing: urdf_DIR)
-- Could not find the required component 'urdf'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "urdf" with any of
  the following names:

    urdfConfig.cmake
    urdf-config.cmake

  Add the installation prefix of "urdf" to CMAKE_PREFIX_PATH or set
  "urdf_DIR" to a directory containing one of the above files.  If "urdf"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  addons/urdfreader/CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
See also "/work/build_ros/CMakeFiles/CMakeOutput.log".
See also "/work/build_ros/CMakeFiles/CMakeError.log".
```

Here Cmake fails to generate a working configuration, due to not finding the URDF code in ROS. 

So the question is what steps are missing to get it working? The should be written in the README in an extra ROS section.

### What I was talking about in my last comment is:
 The URDF Addon consists conceptually in two parts:
1. A URDF Library (statically compiled), it includes the logic to parse URDF files and extract the relevant information. (In this case this Library is provided by ROS). 
2. A Library to use the Information from URDF and translate that into a workable model from RBDLs perspektive (the Addon code, linked against the static URDF parser library)

Anyway that is not really relevant here.

**Comment by rua0ra1** [comment]
Hi @ju6ge ,
All good mate. Thanks for the testing with different ros versions. Coming to the  Ros Noetic, I have tested my PR with following dockerfile and didn't get any build issues.
```docker
# Use the ROS Noetic base image
FROM ros:noetic

# Install required packages
RUN apt update && apt install -y \
    libeigen3-dev \
    ros-noetic-urdf \  
    git

# Source ROS Noetic setup script and add it to the shell initialization script
RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc  

# Set the working directory
WORKDIR /usr/src

# Clone the specific RBDL repository branch
RUN git clone -b urdfreader_bugfix https://github.com/rua0ra1/rbdl.git

# Set the working directory to the cloned repository
WORKDIR /usr/src/rbdl

# Source ROS environment, create the build directory, and configure the project
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && \
    mkdir build && cd build && \
    cmake -DRBDL_USE_ROS_URDF_LIBRARY=ON -DRBDL_BUILD_ADDON_URDFREADER=ON .. && \
    make && make install"
```
And  I believe you are missing 
1) installing ros-noetic-urdf library 
2) sourcing the ros environment before building the file

Coming to jazzy, it is a ros2 version. I am not suprised that it didn't work with ros2 as there are significant difference between both versions.By saying that, I am not very familiar with ros2 but you can try installing the urdf for ros2 version and see whether it gonna works. But, i believe ros related code in the RBDL library is implemented for ros1 not ros2 .So, i don't think it will work with any ros2 versions

Let me know if you need any other information. And I am happy to add separate ros instructions in readme file once I get conformation from your side that it is working . 

Thank you and let me know if you need any other information

**Comment by ju6ge** [comment]
@rua0ra1 

You are correct I was missing `ros-noetic-urdf`. With that everything compiles fine for `ros:noetic`. I would appreciate if you could add a `ROS` section to the RBDL readme. I don't see a reason to also support `ros2` for now, that should be mentioned as well.

**Comment by rua0ra1** [comment]
@ju6ge ,
I have updated the README file with ROS section. Can you have a look at it and let me know your suggestions. Thank you :)

**Review by ju6ge — APPROVED** [review]
Perfekt, I will merge this later and bump the `rbdl` version to a new `patch` level. Thanks!

**Comment by rua0ra1** [comment]
Cheers mate. Thank you :)

**Pull request merged**
