### PR TITLE
Added log to casadi interface

### PR DESCRIPTION
**Pull request by pariterre**
Please, when accepted, I'll need a release on that so I can accept a PR on my own repo :)

Thanks!

### CODE REVIEW

**Comment by pariterre** [comment]
@ju6ge

**Comment by ju6ge** [comment]
Seems straight forward ;) … so I see no issues merging this right away :muscle:

**Comment by ju6ge** [comment]
I merged it and moved the v3.2.1 pre release to the newest commit as well as marking it as the new official release. Does that work for you?

**Comment by pariterre** [comment]
As long as the Conda is triggered I am okay, otherwise I have to wait

**Comment by pariterre** [comment]
Thanks a log @ju6ge !

**Pull request merged**
