### PR TITLE
Make urdfreader compatible with ubuntu 18.04

### PR DESCRIPTION
**Pull request by graiola**

### CODE REVIEW

**Comment by martinfelis** [comment]
Awesome, thanks! We're currently setting up some continuous integration checks and want to run this through it. But we'll definitely merge it in.

**Comment by graiola** [comment]
Hi @martinfelis, this pr should work with 2.5.0 and 2.6.0.
Thank you!

**Review by Vishnuparammal — APPROVED** [review]
I tried this and it compiled beautifully for me. Solved the errors I was facing earlier.

**Comment by liesrock** [comment]
Hi guys! Thanks @graiola for the pr, I believe it should be merged as soon as you can since it is the only way to have rbdl working on 18.04

**Comment by ju6ge** [comment]
I don't think this is still required after the merge of #50. Correct me if I am wrong ;)

**Pull request closed without merging**
