### PR TITLE
Making RBDL fit for Lua version 5.3

### PR DESCRIPTION
**Pull request by DanHauer**
Dear Developer

in rbdl/addons/luamodel/CMakeLists.txt we have changed "FIND_PACKAGE (Lua51 REQUIRED)" to "FIND_PACKAGE (Lua 5.1 REQUIRED)". 
Furthermore, the following three files were copied from /usr/share/cmake-3.10/Modules to rbdl/CMake:
- FindLua.cmake
- FindPackageHandleStandardArgs.cmake
- FindPackageMessage.cmake

This should make Lua 5.3 usable, too.

Best
Daniel

### CODE REVIEW

**Comment by martinfelis** [comment]
Hi Daniel,

thanks for your pull request. The files in `/usr/share/cmake-3.10/Modules` should already be available when running cmake so there should be no need to copy them into the `CMake/` folder of RBDL.

Does the LuaModel addon otherwise work with Lua versions 5.1 - 5.3?

Regards,
Martin

**Comment by paulmanns** [comment]
Hi Martin.

The files are not necessarily present if cmake older than version 3 is present. It appears that RBDL still supports cmake 2.6 and thus the files are needed I guess.

Best,
Paul

**Comment by paulmanns** [comment]
Ok. Please do not accept the pullrequest for now. There is a problem since lua5.1/lua.h include is hardcoded into luamodel.cc

**Comment by martinfelis** [comment]
Setting CMake >= 3.0 as a requirement is fine for RBDL. We should not get stuck in too old stuff.

**Comment by martinfelis** [comment]
Minor update: the recent dev into master merge has fulfilled the CMake >= 3.0 version. So assuming those file exist is fine.

**Comment by DanHauer** [comment]
I removed the three obsolete files.
This caused extra commits. Can they be fused into one commit somehow?

**Comment by mkudruss** [comment]
Hi Daniel,
thanks for the changes. You can indeed "squash" the commits together, see [here](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history).
I'd suggest the following (when this is your first time doing this copy the repo locally to be able to play around with it):

1. You should sync your changes with the upstream repo, see [here](https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa).
2. You should squash everything to a single commit (if possible) and provide a meaningful commit message, see [here](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)
3. Once done you need to force push this to your fork (rewriting history in this case is fine)

Best
Manuel

**Comment by DanHauer** [comment]
Hello,

I tried to squash them, but obviously I did so to a commit of @martinfelis. 

Shall I correct it?

Daniel

**Comment by DanHauer** [comment]
I close this pull request to create a new one where only the one change "FIND_PACKAGE (Lua51 REQUIRED)" to "FIND_PACKAGE (Lua 5.1 REQUIRED)" is.

**Pull request closed without merging**
